// <auto-generated />
namespace DatabaseManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0022));
        
        string IMigrationMetadata.Id
        {
            get { return "201606181426273_0022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
