// <auto-generated />
namespace DatabaseManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0025 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0025));
        
        string IMigrationMetadata.Id
        {
            get { return "201606221746436_0025"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
