// <auto-generated />
namespace TrivialWikiAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0009));
        
        string IMigrationMetadata.Id
        {
            get { return "201605301758548_0009"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
