# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Threshold', models.IntegerField(default=0)),
                ('Icon', models.BinaryField()),
            ],
        ),
    ]
