# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrivialAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=400)),
                ('CorrectAnswer', models.CharField(max_length=50)),
                ('FillerAnswers', models.CharField(max_length=200)),
                ('UsageCount', models.IntegerField(default=0)),
                ('CorrectAnswerCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('TopicQuestions', models.ManyToManyField(to='TrivialAPI.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('SecurityToken', models.CharField(max_length=50)),
                ('Sex', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Avatar', models.BinaryField()),
                ('Points', models.IntegerField(default=0)),
                ('Rank', models.IntegerField()),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.Role')),
            ],
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='TopicId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.Topic'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='User',
            field=models.ManyToManyField(to='TrivialAPI.User'),
        ),
    ]
