# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrivialAPI', '0002_auto_20160223_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wins', models.IntegerField(default=0)),
                ('GamesPlayed', models.IntegerField(default=0)),
                ('WinsInARow', models.IntegerField(default=0)),
                ('BestTopicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_topic_Id', to='TrivialAPI.Topic')),
                ('MostPlayedTopicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_played_topic', to='TrivialAPI.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='StatisticsId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.Statistics'),
        ),
    ]
