# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrivialAPI', '0003_auto_20160223_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageText', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionCount', models.IntegerField()),
                ('LoserCorrectAnswers', models.IntegerField()),
                ('WinnerCorrectAnswers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageText', models.CharField(max_length=500)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='_user_Friends_+', to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='UserTopics',
            field=models.ManyToManyField(default=None, to='TrivialAPI.Topic'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='FirstUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='SecondUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='ChatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.PrivateChat'),
        ),
        migrations.AddField(
            model_name='message',
            name='SenderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='Loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='TopicId',
            field=models.ManyToManyField(to='TrivialAPI.Topic'),
        ),
        migrations.AddField(
            model_name='match',
            name='Winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='TrivialAPI.User'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrivialAPI.User'),
        ),
    ]
